apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
  - name: alpine
    image: alpine  
    volumeMounts:
      - name: html
        mountPath: /html
    command: [ "/bin/sh", "-c" ]      
    args:
      - while true; do
        echo $(hostname) $(date) >> /html/index.html;
        sleep 10;
        done
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
