apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    env:
    - name: value # pod 裡面的變數名稱
      valueFrom:
        configMapKeyRef:
          name: mycmliteral # config map 名稱
          key: var1 # config map 裡的變數名稱  
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
